### ISSUE TITLE
Missing types for AStarPathfindingProject breaking build

### ISSUE THREAD

**Issue by cofl** [HuskyGameDev/2019f-team10#23]
Several types appear to be missing for AStarPathfindingProject, which is causing compilation failures and generally breaking things.

The bug appears to have been introduced in 01c6351421b8c2879aa0ea4130e71495710fc974.

Missing types/namespaces are:

- `Pathfinding.Ionic` namespace
- `ZipFile` class
- `ZipOption` class
- `ZipEntry` class

**Comment by cofl** [comment]
I think this may have to do with faulty settings in the `.gitattributes` file, which is my fault.

**Comment by cofl** [comment]
I fixed the attributes file and re-committed your changes, @tjmareng. Could you please check that everything's as it should be onthe master branch?

**Comment by tjmareng** [comment]
I am still getting AStarPathfindingProject reference errors.

**Comment by tjmareng** [comment]
I believe I resolved this issue. Could you confirm this?
